
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: ./Dockerfile
    container_name: frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - backend


  backend:
    build:
      context: ./back-end
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db